- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_execute.py
- python/letsql/expr/translate.py
- python/letsql/optimizer/tests/test_optimize.py
The implementation transforms the SQL into a binded ibis expr using the DataFusion parser and plan_to_ibis
closes #23
> feat: add .sql implementation

- examples/local_cache.py
- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_execute.py
- python/letsql/common/collections.py
- python/letsql/common/utils/dask_normalize_expr.py
- python/letsql/expr/relations.py
> fix: mismatched table names causing table not found error

- .envrc
- pyproject.toml
- python/letsql/backends/conftest.py
- python/letsql/backends/let/tests/conftest.py
- python/letsql/backends/let/tests/test_cache.py
- python/letsql/backends/let/tests/test_client.py
- python/letsql/backends/let/tests/test_execute.py
- python/letsql/backends/snowflake/tests/conftest.py
- python/letsql/backends/snowflake/tests/test_cache.py
- python/letsql/common/utils/dask_normalize_expr.py
- python/letsql/common/utils/snowflake_utils.py
feat: add snowflake_utils
test: add test for snowflake cache invalidation
> feat: add better snowflake caching

- python/letsql/backends/snowflake/hotfix.py
- python/letsql/backends/snowflake/tests/test_client.py
- python/letsql/common/utils/snowflake_utils.py
- add a hotfix for proper snowflake connection initialization (pending next release that includes https://github.com/ibis-project/ibis/pull/9221)
- add a test for expectation of initial snowflake connection state re catalog/database based on `create_object_udfs`
> snowflake setup session hotfix

- python/letsql/backends/datafusion/compiler.py
- python/letsql/tests/test_array.py
- flatten
- range
- array_distinct
- unnest
- array_slice
> feat: add array functions

- python/letsql/backends/let/tests/test_cache.py
- python/letsql/common/utils/dask_normalize_expr.py
- python/letsql/common/utils/logging_utils.py
- enable normalization of duckdb memory tables
- add tests for caching of duckdb tables
- add test of cross source storage
> test cross source storage

- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_isolated_execution.py
> hotfix: problem with multi-engine execution

- python/letsql/backends/datafusion/compiler.py
- python/letsql/tests/test_numeric.py
- python/letsql/tests/test_temporal.py
- python/letsql/tests/util.py
> feat: add numeric functions

- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_cache.py
> fix read_parquet/csv/delta and cache

- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_execute.py
> fix: register table on caching nodes

- Cargo.lock
- Cargo.toml
- python/letsql/backends/datafusion/compiler.py
- python/letsql/tests/test_numeric.py
- src/context.rs
- src/functions.rs
- src/functions/greatest.rs
- src/functions/least.rs
- src/lib.rs
Add functions:
- greatest
- least
> feat: add greatest and least functions

- python/letsql/backends/datafusion/compiler.py
- python/letsql/tests/test_temporal.py
- bucket
- to_date
- to_timestamp
> feat: add temporal functions

- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_execute.py
> fix: register cache tables when executing to_pyarrow

- examples/postgres_caching.py
- python/letsql/backends/postgres/__init__.py
The method will create a temporary table in PostgreSQL.
> In PostgreSQL, a temporary table is a table that exists only during a database session. It is created and used within a single database session and is automatically dropped at the end of the session.
> feat: add postgres read_parquet

- .github/workflows/ci-publish.yml
- CONTRIBUTING.md
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207865787473515
> chore: change to publish on release

- poetry.lock
- pyproject.toml
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207812252857351
> chore: update dependencies ranges

- README.md
- poetry.lock
- pyproject.toml
- python/letsql/__init__.py
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207812252857363
> chore: enable plugin development for backends

- python/letsql/backends/datafusion/__init__.py
- python/letsql/backends/datafusion/tests/test_provider.py
+ `con.register_xgb_model` that returns an ibis udf.
> feat: add ibis udf and model registration method

- python/letsql/backends/datafusion/__init__.py
- python/letsql/backends/datafusion/tests/test_provider.py
```python
In [1]: import letsql as ls ; con = ls.connect()
In [2]: predict_xgb = con.register_xgb_model("diamonds_model", "../experiment-diamonds.json"); predict_xgb
Out[2]: <function functools.register_xgb_model(carat: Float64(nullable=True), depth: Float64(nullable=True), x: Float64(nullable=True), y: Float64(nullable=True), z: Float64(nullable=True))>
In [3]: help(predict_xgb)
Out[3]: 
Help on function diamonds_model in module functools:
diamonds_model(carat: Float64(nullable=True), depth: Float64(nullable=True), x: Float64(nullable=True), y: Float64(nullable=True), z: Float64(nullable=True))
```
> feat(udf): add udf signature and return a partial with model_name

- python/letsql/backends/let/__init__.py
- python/letsql/tests/test_register.py
> fix: registration of in-memory tables

- flake.nix
as well as addressing the `/homeless-shelter` warning from ipython
> fix pins ssl and cache

- python/letsql/tests/test_register.py
- src/context.rs
- src/object_storage.rs
> feat: add reading parquet from http

- examples/xgboost_udaf.py
- python/letsql/backends/let/tests/snapshots/test_cache/test_udaf_caching/test_udaf_caching.txt
- python/letsql/backends/let/tests/test_cache.py
- python/letsql/backends/let/tests/test_udf.py
- python/letsql/expr/udf.py
and accept schema rather than expr
> ref: udf.agg.pandas_df: enable use as a decorator

- python/letsql/backends/duckdb/__init__.py
- python/letsql/backends/let/__init__.py
- python/letsql/backends/let/tests/test_execute.py
- python/letsql/common/utils/defer_utils.py
- python/letsql/expr/api.py
- python/letsql/expr/relations.py
- python/letsql/optimizer/tests/test_optimize.py
- python/letsql/tests/test_into_backend.py
> fix: to_pyarrow_batches

- examples/quickgrove_udf.py
- python/letsql/common/utils/name_utils.py
- python/letsql/expr/ml.py
- python/letsql/tests/conftest.py
- python/letsql/tests/test_ml.py
> fix: convert name to valid Python identifier

- python/letsql/common/utils/dask_normalize_expr.py
unclear why dictionary was not giving a stable hash
> fix(caching): ensure stable hash for normalize_read

- python/xorq/vendor/ibis/expr/types/core.py
> fix: default_backend should xorq

- python/xorq/flight/action.py
- python/xorq/flight/backend.py
- python/xorq/flight/client.py
- python/xorq/flight/tests/test_actions.py
> fix: make action_body a dict

- python/xorq/flight/exchanger.py
> chore: remove unused exchangers

- docs/docs.json
- docs/vignettes/duckdb_concurrent.mdx
> docs: add multi-duck vignette

- python/xorq/backends/let/tests/test_cache.py
- python/xorq/ibis_yaml/tests/conftest.py
- python/xorq/ibis_yaml/tests/test_compiler.py
- python/xorq/tests/test_profile.py
- python/xorq/vendor/ibis/expr/types/core.py
> fix: spurious backend in _find_backend

- python/xorq/cli.py
- python/xorq/tests/test_cli.py
> feat(cli): add top level --pdb: drop into post mortem on failure

- examples/flight_udtf_llm_example.py
- pyproject.toml
- requirements-dev.txt
- uv.lock
> refactor: remove tenacity from examples

- python/xorq/ibis_yaml/udf.py
> ref(cli): factor out helpers

- python/xorq/ibis_yaml/udf.py
- python/xorq/tests/test_cli.py
> feat(cli): enable exprscalarudf

- flake.nix
- nix/letsql.nix
and fix `impure` shell by adding common libs
> feat(nix): add virtualenv-default

- .github/workflows/ci-test-library.yml
This prevents issues with missing files or dependencies.
closes #240
> chore(test): test library as an installed wheel

- python/xorq/ibis_yaml/compiler.py
- python/xorq/ibis_yaml/tests/test_compiler.py
- python/xorq/ibis_yaml/translate.py
> fix(compiler): register translation for PosixPath

- python/xorq/ibis_yaml/tests/test_string_ops.py
- python/xorq/ibis_yaml/translate.py
> feat(compiler): support StringToDate in build

- python/xorq/backends/let/tests/snapshots/test_cache/test_udaf_caching/py310_test_udaf_caching.txt
- python/xorq/backends/let/tests/snapshots/test_cache/test_udaf_caching/py311_test_udaf_caching.txt
- python/xorq/backends/let/tests/snapshots/test_cache/test_udaf_caching/py312_test_udaf_caching.txt
- python/xorq/backends/let/tests/snapshots/test_cache/test_udf_caching/py310_udf_caching.txt
- python/xorq/backends/let/tests/snapshots/test_cache/test_udf_caching/py311_udf_caching.txt
- python/xorq/backends/let/tests/snapshots/test_cache/test_udf_caching/py312_udf_caching.txt
- python/xorq/backends/let/tests/test_cache.py
- python/xorq/caching/__init__.py
> fix(cache): remove double prefix

- python/xorq/backends/let/datafusion/compiler.py
- python/xorq/tests/test_array.py
> feat: add ArrayAny and ArrayAll to xorq backend

- python/xorq/ibis_yaml/common.py
- python/xorq/ibis_yaml/tests/test_arithmetic.py
- python/xorq/ibis_yaml/tests/test_basic.py
- python/xorq/ibis_yaml/tests/test_operations_boolean.py
- python/xorq/ibis_yaml/tests/test_operations_cast.py
- python/xorq/ibis_yaml/tests/test_operations_datetime.py
- python/xorq/ibis_yaml/tests/test_string_ops.py
- python/xorq/ibis_yaml/tests/test_subquery.py
- python/xorq/ibis_yaml/translate.py
- python/xorq/ibis_yaml/udf.py
> fix(compiler): change _translate_type to translate yaml

- python/xorq/ibis_yaml/tests/test_operations_boolean.py
- python/xorq/ibis_yaml/translate.py
> feat(compiler): add IsInf and IsNan ops

- examples/duckdb_flight_example.py
- python/xorq/flight/__init__.py
- python/xorq/flight/client.py
- python/xorq/flight/tests/test_basic.py
- python/xorq/flight/tests/test_server.py
Enables `xorq.flight.connect`
closes #919 
closes #920
> fix: flight server issues

- python/xorq/common/utils/graph_utils.py
- python/xorq/ibis_yaml/compiler.py
- python/xorq/ibis_yaml/tests/test_compiler.py
> fix(compiler): enable building of DatabaseTable

- .codespell.ignore-words
- examples/bank_marketing.py
- examples/deferred_fit_predict_example.py
- examples/deferred_fit_transform_predict_example.py
- examples/pipeline_example.py
- examples/pipeline_example_SelectKBest.py
- examples/pipeline_example_set_params.py
- flake.nix
- nix/letsql.nix
- python/xorq/common/utils/dask_normalize/dask_normalize_utils.py
- python/xorq/expr/ml/__init__.py
- python/xorq/expr/ml/fit_lib.py
- python/xorq/expr/ml/pipeline_lib.py
- python/xorq/expr/ml/quickgrove_lib.py
- python/xorq/expr/ml/split_lib.py
- python/xorq/expr/udf.py
> feat(ml): add pipeline

- python/xorq/backends/pandas/__init__.py
- python/xorq/expr/api.py
- python/xorq/ibis_yaml/sql.py
- python/xorq/ibis_yaml/tests/test_compiler.py
> fix(compiler): build for non SQL backends

- python/xorq/common/utils/tests/test_tls_utils.py
- python/xorq/common/utils/tls_utils.py
> feat(tls): add TSLKwargs to_disk and from_disk

- python/xorq/ibis_yaml/tests/test_compiler.py
- python/xorq/ibis_yaml/translate.py
> fix(cli): structfield

- python/xorq/backends/let/datafusion/compiler.py
- python/xorq/examples/__init__.py
- python/xorq/examples/tests/test_examples.py
> fix(examples): fetch penguins

- pyproject.toml
- uv.lock
FlightUDXF.from_expr uses TLSKwargs which requires cryptography
fixes #1121
> fix(deps): add cryptography as a core dependency

- python/xorq/cli.py
- python/xorq/flight/__init__.py
- python/xorq/tests/test_cli.py
> fix(cli): port and host args handling

- docs/tutorials/getting_started/quickstart.qmd
> docs(quickstart): remove row_number hack for gen_splits

- python/xorq/tests/test_sql.py
- python/xorq/vendor/ibis/expr/types/relations.py
> fix: .sql on deferred_read_* nodes

- python/xorq/ibis_yaml/tests/test_basic.py
- python/xorq/ibis_yaml/tests/test_relations.py
- python/xorq/ibis_yaml/translate.py
> fix(yaml): support group by alias in aggregate

- python/xorq/common/utils/tests/test_deferred_read.py
- python/xorq/ibis_yaml/tests/test_letsql_ops.py
- python/xorq/ibis_yaml/translate.py
> feat(compiler): warn when a Read op targets a local file

- examples/bank_marketing.py
- python/xorq/expr/ml/pipeline_lib.py
- python/xorq/expr/ml/tests/test_step.py
enable accessing `FittedStep.model` property for uncached (no storage) models
> fix(ml): uncached fittedstep model

- python/xorq/expr/relations.py
- python/xorq/expr/tests/test_relations.py
- python/xorq/ibis_yaml/tests/test_relations.py
> chore: add better error message for ValueError

- python/xorq/backends/let/tests/test_udf.py
- python/xorq/expr/udf.py
- python/xorq/tests/fixtures/pipeline_pandas_udf.py
> fix(xorq): add valid default xorq.expr.udf.agg.pandas_df name

- python/xorq/backends/pandas/tests/test_ops.py
- python/xorq/expr/ml/split_lib.py
- python/xorq/expr/ml/tests/test_split_lib.py
- python/xorq/vendor/ibis/backends/pandas/helpers.py
- python/xorq/vendor/ibis/backends/pandas/kernels.py
> fix(split lib): train test splits pandas

- python/xorq/common/utils/snowflake_utils.py
- python/xorq/ibis_yaml/translate.py
> fix(ibis_yaml): Distinct: register from_yaml loader
