xorq-labs/xorq

python/letsql/backends/datafusion/__init__.py, python/letsql/backends/datafusion/provider.py, python/letsql/backends/datafusion/tests/test_provider.py, python/letsql/internal.py, src/context.rs, src/ibis_filter_expression.rs, src/lib.rs, src/provider.rs, src/py_record_batch_provider.rs, src/udaf.rs
The objective is to be able to debug the code, and make it easy to extend.
The debug-ability of the code was tested manually via pdb with `breakpoint()`.
Additionally this PR does some refactoring.
The `register_ibis_table` will deprecated in the future.
closes #25
=> feat: expose TableProvider trait in Python

flake.nix
Fixes missing source files  `README.md` and `LICENSE` from nix flake.
=> fix: mac build with missing source files

python/letsql/optimizer/tests/test_predict.py
loss function used by XGBoost is `reg::squarederror`, formerly called `reg:linear`
=> chore(predict): objective function is being deprecated

README.md, examples/local_cache.py, examples/multi_engine.py, python/letsql/backends/let/__init__.py, python/letsql/backends/let/tests/conftest.py, python/letsql/backends/let/tests/test_cache.py, python/letsql/backends/let/tests/test_execute.py
Since LetSQL now has the capacity for adding ibis `ir.Table` as a `TableProvider`
we can drop the connection management, this is good because:
- it simplifies the code, no need to handle the connection directly
- from the UX point of view the user doesn't need to add a static reference
- The user doesn't need to learn a new set of methods
Now every time a table is registered, we add the original backend to keep
track of it, to execute single-backend queries on the original
source.
As of now directly executing on the original backend generates issues
when the table name changes (the `test_register_already_existing_table` fails).
So the execution goes through the to_pyarrow_batches method.
Additionally this commit removes unused code and parameters.
=> feat: drop connection handling

python/letsql/backends/let/__init__.py, python/letsql/backends/let/tests/test_execute.py, src/context.rs, src/dataframe.rs, src/utils.rs
**Why was a letsql table being executed only once?**
Because when executing the `TableProvider for IbisTable` it would raise:
> Cannot start a runtime from within a runtime. This happens because a function
> (like block_on) attempted to block the current thread while the thread is being
> used to drive asynchronous tasks.
**Why the current code was implemented?**
Because in contrast to `IbisTable`, the `TableProvider for PyRecordBatchProvider`
would not raise an exception, but it had the downside of only being able to
execute it once.
Note there was a TODO to improve it in the future:
```python
```
**Why the `IbisTable` raised an exception and the `PyRecordBatchProvider` not?**
The best guess is that the IbisTable calls `to_pyarrow_batches`, so there was
a nested call `to_pyarrow_batches` …
=> fix: allow for multiple execution of letsql tables

examples/simple_example.py, python/letsql/tests/test_examples.py
In the past code changes have broken the scripts in the example directory
This commit ensures code changes won't break example functionality without breaking the test suite.
Inspired by this
https://x.com/samuel_colvin/status/1785113080696872980
=> chore: add automatic testing for examples dir

flake.nix, poetry.lock, python/letsql/backends/let/tests/conftest.py, python/letsql/backends/let/tests/test_cache.py, python/letsql/common/utils/dask_normalize_expr.py, python/letsql/common/utils/postgres_utils.py
- add better caching of postgres tables by checking information postgres' system catalogs
- add test of postgres cache invalidation upon table modification
- modify conftest to remove all "unexpected" tables from postgres database
- add environment variable to prevent poetry from hanging on keyring issues
=> feat: improve postgres table caching / cache invalidation

python/letsql/backends/datafusion/__init__.py, python/letsql/backends/let/tests/test_client.py
lacking this change, the intermediate `RecordBatch` resulting from `from_arrays` does not respect the nullability of the incoming batch and the subsequent cast complains about the inability to cast from nullable to not-nullable
=> fix: ensure nonnull-ability of columns works

python/letsql/backends/snowflake/tests/test_cache.py, python/letsql/common/utils/snowflake_utils.py
- `get_snowflake_last_modification_time`: add a filter on `TABLE_SCHEMA` to ensure proper identification of the
- `test_snowflake_cache_with_name_multiplicity`: add a test that validates snowflake caching works when multiple tables share a name
=> fix snowflake caching

.pre-commit-config.yaml
```
codespell................................................................Passed
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
Rust fmt.............................................(no files to check)Skipped
Rust clippy..........................................(no files to check)Skipped
poetry-check.............................................................Passed
poetry-lock..............................................................Passed
poetry-export............................................................Failed
- hook id: poetry-export
- files were modified by this hook
Warning: poetry-plugin-export will not be installed by default in a future version of Poetry. …
```
=> fix(pre-commit): explicitly install poetry-plugin-export per warning

python/letsql/common/caching.py
else the storage source will try to compile the cached expr with its own dialect
=> feat: SourceStorage: special case for cross-source caching

python/letsql/common/utils/dask_normalize_expr.py, python/letsql/common/utils/tests/test_dask_normalize.py
rather than pull of all the table into memory at once, tokenize batches generated by `to_pyarrow_batches`
=> fix: normalize_memory_databasetable: incrementally tokenize RecordBatchs

python/letsql/backends/datafusion/__init__.py, python/letsql/backends/let/__init__.py, python/letsql/backends/let/tests/test_client.py, python/letsql/internal.py, src/context.rs, src/lib.rs
Currently creating a table results in the following PanicException
```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
that is because we don't use Tokio when executing a SQL query,
to be able to register LETSQL tables inside LETSQL
The solution is to treat the registration of DataFusion-backed tables
separately and use the original table to avoid calling to py_arrow_batches
closes #71
=> fix: cannot create table

python/letsql/backends/let/__init__.py
The updating/setting of the correct value for the table already happens inside the register method.
=> fix: remove redundant item setting _sources on registering the cache nodes

python/letsql/backends/let/hotfix.py, python/letsql/backends/let/tests/test_cache.py, python/letsql/expr/relations.py
The name `n `clashes with operations/expressions containing arguments with that name, such as limit.
The root of the issue is that the map function creates a `kwargs` dictionary containing as keys the operation's arguments.
When the name of one of the operation's arguments matches the name of the first argument, an issue arises.
=> fix: change name of parameter in replace_table function

Cargo.lock, Cargo.toml, examples/penguins_example.py, poetry.lock, pyproject.toml, python/letsql/backends/let/__init__.py, python/letsql/common/utils/dask_normalize_expr.py, python/letsql/common/utils/logging_utils.py, python/letsql/common/utils/tests/test_dask_normalize.py, python/letsql/common/utils/tests/test_logging.py, python/letsql/config.py, python/letsql/expr/api.py
Letsql use maturin as the build-backend. To handle our dependencies, we use poetry. Currently and in the future, maturin does not recognize the dependencies specified by poetry. See this issue:
https://github.com/PyO3/maturin/issues/632
It also does not provide an alternative way to support dynamic dependencies. The following issue is still open.
https://github.com/PyO3/maturin/issues/1537
On the other side, poetry will support PEP-621 project style dependencies in version 2.0
https://github.com/python-poetry/poetry/issues/3332
Therefore, one simple solution is to duplicate the dependencies section, as in the package:
https://github.com/tmtenbrink/rustfrc/blob/main/pyproject.toml
To do so, a semi-automated approach is used to generate the dependencies using `poetry export`.
```bash
poetry …
```
=> chore: prepare for release 0.1.4

examples/remote_caching.py, python/letsql/backends/let/__init__.py, python/letsql/backends/let/tests/test_execute.py, python/letsql/common/caching.py, python/letsql/common/utils/dask_normalize_expr.py
- create new unit test to detect and fix problems obtained from the workflow diagram analysis
- fixes the problem with using set or equals for testing equality among backends, currently the hashing of backends is based on string of the name of the class, which renders all backends equals
- fix problem normalize_duckdb_databasetable to handle SEQ_SCAN and duckdb tables
- fix node replacement, now it is a LETSQL op. Before calling .cache at the end of expr causes the expr source to become the source of the cache, leaving letsql and entering into ibis.
- also add tests to verify that execution happens in the native backend
workflow diagram reference: https://excalidraw.com/#json=rmcDKw_OB0hoZ7B2O4NKO,TXGXMJ38zb1Ly3NwXgaVcw
=> chore: add unit tests based on workflow diagram

poetry.lock, pyproject.toml
The change was tested on a project with the following pyproject.toml
```toml
[tool.poetry]
name = "test-letsql"
version = "0.1.0"
description = ""
authors = ["Daniel Mesejo <mesejoleon@gmail.com>"]
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.10"
pyarrow = "15.0.0"
letsql = {path = "/home/daniel/PycharmProjects/public-letsql/target/wheels/letsql-0.1.4-cp38-abi3-manylinux_2_35_x86_64.whl"}
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
=> chore: unpin pyarrow version

.github/renovate.json
The manager changes the requirements-dev.txt file, this file is generated automatically from poetry export command, so there is no need to change it manually. Moreover is creating duplicated noisy PRs
=> chore: disable pip_requirements manager

.envrc, flake.nix, nix/letsql.nix, shell.nix
enables editing `.envrc` to use non-flake nix to work with an editable install
```
diff --git a/.envrc b/.envrc
index 8f99741..f4a187e 100644
--- a/.envrc
+++ b/.envrc
@@ -12,6 +12,6 @@ export NIX_CONF_DIR=$(realpath ./nix)
export NIX_USER_CONF_FILES=$(realpath ./nix)
watch_file pyproject.toml poetry.lock
watch_file nix/commands.nix
-use flake
+# use flake
-# use nix
+use nix
```
=> nix editable install

python/letsql/backends/let/__init__.py, python/letsql/backends/let/tests/test_cache.py, python/letsql/common/caching.py
**Why was the setting as the source of the SourceStorage cache failing?**
The pandas backend needs to learn how to create a table from an ibis expression.
**Why do we need to execute the unbound expr?**
The panda's executor assumes the expr is bound to pandas and will search for the dictionary attribute.
The SQL backends create an SQL string from the expr.
Moreover, executing unbound expr pushes the code in the right direction.
closes #192
=> fix: use pandas backend in SourceStorage

python/letsql/backends/datafusion/__init__.py
fixed
``` python
<function functools.register_xgb_model(carat: Float64(nullable=True), depth: Float64(nullable=True), x: Float64(nullable=True), y: Float64(nullable=True), z: Float64(nullable=True))>
```
to
```python
<function letsql.backends.datafusion.predict_xgb(carat: Float64(nullable=True), depth: Float64(nullable=True), x: Float64(nullable=True), y: Float64(nullable=True), z: Float64(nullable=True))>
```
=> fix(udf): remove  wrap so that the udf keeps its metadata

.github/workflows/ci-docs-main.yml, .github/workflows/ci-docs-preview.yml, .github/workflows/ci-test-library.yml, pyproject.toml, python/letsql/tests/test_examples.py
The `extras` and `dev,test` dependencies add additional dependencies that may not be present with a library install 
(`pip install letsql`).
This commit aims to add a workflow for testing the library only using the specified dependencies (not including the one in the examples extra).
Additionally, it adds `--release` to the poetry maturin build to speed up the tests.
=> chore: add workflow for testing library only dependencies

examples/postgres_caching.py, examples/predict_xgb.py
Executing the examples creates a letsql-tmp directory, that makes into the changes on git. Use a TemporaryDirectory instead
=> chore: use postgres.connect_examples() and TemporaryDirectory

.github/workflows/ci-test-s3.yml
When running with the ci-test-s3, the commit's SHA should point to PR HEAD
=> fix: checkout PR ref

nix/letsql.nix
restore working nix build on linux by making `Security` an `isDarwin` optional
=> fix(nix): enable build on linux

.github/workflows/ci-test-library.yml, examples/remote_caching.py
This PR only uses `pip` and `venv` to verify the library is installed correctly. 
1. The first step is to install `pytest` and `maturin`
2. Execute `maturin develop` to install letsql in development mode
3. Execute some of the examples to verify the correct installation 
This will fail if a `dependency` is specified in `poetry` and not in the `dependencies`.
=> chore: ci check for right install

.github/workflows/ci-test-examples.yml, .github/workflows/ci-test-library.yml, .github/workflows/ci-test.yml
PRs from forked repositories cannot access secrets [[1]](https://michaelheap.com/access-secrets-from-forks/)
Currently we are using secrets to store default credentials to access the PostgreSQL Docker instance, since these values are not secrets we should store them in vars, to make them accesible from forked repositories.
=> chore: use vars instead of secrets

.github/renovate.json
Since we are using Rust to create Python packages, a particular version of the package is selected at compile time, so we don't need to provide a range of dependencies for Cargo.
=> chore: pin cargo dependencies version

uv.lock
update jinja2 due to security issues:
- Jinja has a sandbox breakout through indirect reference to format method
- Jinja has a sandbox breakout through malicious filenames
=> chore: uv lock --upgrade-package jinja2

examples/train_test_splits.py, python/letsql/expr/api.py, python/letsql/expr/ml.py, python/letsql/tests/conftest.py, python/letsql/tests/test_ml.py
This PR adds functionality for a train test split to letsql. 
I have not updated the crate to bump semantic version.
```python
import letsql as ls 
table = memtable([(i, "val") for i in range(N)], columns=["key1", "val"])
train_table, test_table = ls.train_test_split(
table, unique_key="key1", test_sizes=test_size, random_seed=42
)
```
There was a name space conflict of some sort so there is some odd imports at the top `api.py` , this will be fixed. 
It needs more tests on errors & maybe a warning about how bin size & its impact on  train test split percentages, but. I wanted to get something out there to receive feedback. 
if `test_size` is a `float` you will get back   train , test sets with a proportion of (1 - test_size) , ( test_size) 
Otherwise `test_sizes` must be an iterable of …
=>  Feature implement train test split

pyproject.toml
By setting `select`, we overwrite **ruff** default rules:
```toml
["E4", "E7", "E9", "F"]
```
Instead, we should use `extend-select`  to preserve default rules:
```
[tool.ruff.lint]
extend-select = ["I", "ICN"]
```
=> chore: extend ruff select rules instead of overwriting

requirements-dev.txt, uv.lock
Snowflake discovered and remediated a vulnerability in the Snowflake Connector for Python. A function from the snowflake.connector.pandas_tools module is vulnerable to SQL injection. This vulnerability affects versions 2.2.5 through 3.13.0. Snowflake fixed the issue in version 3.13.1.
**Vulnerability Details**
A function from the snowflake.connector.pandas_tools module is not sanitizing all of its arguments, and queries using them are not parametrized. An attacker controlling these arguments could achieve SQL injection by passing crafted input. Any SQL executed that way by an attacker would still run in the context of the current session.
**Solution**
Snowflake released version 3.13.1 of the Snowflake Connector for Python, which fixes this issue. We recommend users upgrade to version …
=> chore: snowflake-connector-python security update

python/letsql/backends/let/datafusion/__init__.py, python/letsql/backends/let/tests/test_client.py, python/letsql/common/utils/dask_normalize_expr.py, src/context.rs, src/expr.rs, src/expr/sort_expr.rs, src/py_record_batch_provider.rs, src/utils.rs
This enables parent plans in DataFusion to take advantage of the
sortedness of the RecordBatchReader.
closes #470
=> feat: add ordering arg to register_record_batch_reader

.github/workflows/ci-test-examples.yml, .github/workflows/ci-test-library.yml, examples/deferred_read_csv.py, examples/multi_engine.py, examples/remote_caching.py, examples/simple_example.py, examples/xgboost_udaf.py, python/letsql/examples/__init__.py, python/letsql/examples/core.py, python/letsql/examples/tests/test_examples.py, python/letsql/tests/test_examples.py
Wrapping provides a better UX, due to the following reasons:
- less code, hide repetitive code
- the user does not need to know the type (csv, parquet) of the file
- the user can know which examples are available via tab completion on the examples package
=> chore: wrap pins with examples

python/xorq/ibis_yaml/common.py, python/xorq/ibis_yaml/compiler.py, python/xorq/ibis_yaml/tests/test_basic.py, python/xorq/ibis_yaml/tests/test_benchmark.py, python/xorq/ibis_yaml/tests/test_relations.py, python/xorq/ibis_yaml/tests/test_subquery.py, python/xorq/ibis_yaml/tests/test_window_functions.py, python/xorq/ibis_yaml/translate.py
example expr.yaml file with nodes:
```python
from xorq.ibis_yaml.compiler import BuildManager
from xorq.common.utils.defer_utils import deferred_read_parquet
parquet_path = ls.config.options.pins.get_path("awards_players")
backend = ls.duckdb.connect()
awards_players = deferred_read_parquet(backend, parquet_path, table_name="awards_players")
expr = awards_players.playerID.count()
```
```yaml
definitions:
schemas:
schema_0:
playerID:
name: String
nullable: true
awardID:
name: String
nullable: true
yearID:
name: Int64
nullable: true
lgID:
name: String
nullable: true
tie:
name: String
nullable: true
notes:
name: String
nullable: true
nodes:
20b6b103e6b3f2b3f511fba4ca3a854a:
op: Field
name: playerID
relation:
op: Read
method_name: read_parquet
name: awards_players
schema_ref: schema_0 …
```
=> fix: dedupe yaml seralization

docs/api-reference/profiles-api.mdx, docs/docs.json, docs/tutorials/profiles_guide.mdx
This adds a user guide and API doc to our docs.
It is still dependent on pull  #570  before the docs will work for users.
=> feat: profile docs& guide

python/xorq/expr/api.py, python/xorq/tests/test_api.py, python/xorq/vendor/ibis/expr/types/core.py
Our `to_json` differs from the current ibis `to_json`, we chose ndjson as opposed to json array because:
- datafusion writes/reads ndjson
- duckdb writes ndjson (can also write json arrays)
- pyarrow only reads ndjson
- pandas can do both
=> feat: add to_json/to_csv

python/xorq/backends/postgres/tests/test_cache.py, python/xorq/caching/__init__.py, python/xorq/examples/core.py
dt.Array(dt.float64) causes failures
running
```
import xorq as xo                  
from xorq.caching import SourceStorage                                                                                                      
from xorq.common.utils.defer_utils import deferred_read_parquet       
from xorq.common.utils.import_utils import import_python              
m = import_python(xo.options.pins.get_path("hackernews_lib"))         
name = "hn-fetcher-input-large"                                       
con = xo.connect()                                                    
pg = xo.postgres.connect_env()     
t = (                                                                 
deferred_read_parquet(         
con, …
```
=> fix(caching): special case for postgres in case of complex types

python/xorq/vendor/ibis/backends/profiles.py
While running:
```python
import xorq as xo
from xorq.common.utils.defer_utils import deferred_read_parquet
from xorq.expr.relations import into_backend
from xorq.ibis_yaml.compiler import BuildManager
```
I recieved the error:
```bash
[/home/al/repos/xorq/xorq_playground/venv/lib/python3.12/site-packages/xorq/vendor/ibis/backends/profiles.py:23](http://localhost:8888/home/al/repos/xorq/xorq_playground/venv/lib/python3.12/site-packages/xorq/vendor/ibis/backends/profiles.py#line=22): SyntaxWarning: invalid escape sequence '\$'
compiled_env_var_re = re.compile("^(?:\${(.*)}$)|(?:\$(.*))$")
```
It was a very small change to make sure the regex expression was using the raw string.
=> fix: warning for not using raw string in regex

python/xorq/backends/postgres/__init__.py
enables users to use hit the examples server for caching with
```
pg = xo.postgres.connect_examples(database="caching")
```
=> feat(postgres): connect_examples: pass kwargs

Cargo.lock, Cargo.toml, python/xorq/backends/let/tests/test_cache.py, python/xorq/common/utils/dask_normalize/dask_normalize_expr.py, src/expr.rs, src/expr/aggregate.rs, src/expr/aggregate_expr.rs, src/expr/window.rs
Had to change the function `normalize_datafusion_databasetable`
because the output of the `execution_plan` function also changed.
DataFusion 46 has a `file_type` field; the name has changed
to DataSourceExec.
=> chore: update to datafusion 46

.github/workflows/ci-pre-release.yml, .github/workflows/ci-release.yml
Specifying the PATCH version in python-version causes failures in Windows:
Reference: https://github.com/xorq-labs/xorq/actions/runs/14636033043
=> chore: use python 3.10

pyproject.toml, requirements-dev.txt, uv.lock
Since `UrlOperatorExchanger`, `RowSumExchanger`, and `RowSumAppendExchanger `  were removed, the only step is to ensure the requests package is installed for the `examples` extra.
closes #696
=> chore(deps): ensure requests is installed for examples

README.md
When running through the README, this section was giving me a `AttributeError: 'LETSQLAccessor' object has no attribute 'backend'`. I added the "s".
```
---------------------------------------------------------------------------
In [2]: pandas_con = xo.pandas.connect()
AttributeError                            Traceback (most recent call last)
Cell In[2], line 12
...
---> 12 print(expr.ls.backend)
AttributeError: 'LETSQLAccessor' object has no attribute 'backend'
In [3]: print(expr.ls.backends)
(<xorq.backends.pandas.Backend object at 0x103701a90>,)
```
=> fix(docs): correct backend reference in README

python/xorq/cli.py
simply printing the exception won't always give meaningful information and sometimes seems like a silent sucess
=> fix(cli): use print_exc

python/xorq/caching/__init__.py, python/xorq/common/utils/dask_normalize/dask_normalize_utils.py, python/xorq/common/utils/node_utils.py, python/xorq/flight/exchanger.py, python/xorq/vendor/ibis/expr/types/core.py
patches normalize_op to be cached for a single top level invocation
=> feat(xorq): LETSQLAccessor: add property `tokenized`

compose.yaml
The Bitnami Catalog was deleted on the 29th of September, this means we need to use the Bitnami Legacy Catalog
=> chore(deps): change Bitnami Catalog (docker images)
